default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: testdb
  username: testuser
  password: testuser

test:
  <<: *default
  database: testdb
  username: testuser
  password: testuser

production:
  <<: *default
  database: testdb
  username: testuser
  password: testuser
